# Generated by Django 6.0.5 on 2026-09-30 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('target_role', models.CharField(max_length=200)),
                ('secondary_role', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('college', models.CharField(blank=True, max_length=300)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('current_ctc', models.CharField(blank=True, help_text='e.g., 4 LPA or $60k', max_length=100)),
                ('expected_ctc', models.CharField(blank=True, help_text='e.g., 8 LPA or $80k', max_length=100)),
                ('notice_period', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('selected_plan', models.CharField(choices=[('normal', 'Normal Apply'), ('cold', 'Cold Apply'), ('both', 'Full-Throttle Sprint'), ('budget', 'Budget-Friendly / Custom')], max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('whatsapp_connected', 'WhatsApp Connected'), ('active', 'Active Campaign'), ('paused', 'Paused'), ('completed', 'Completed')], default='registered', max_length=30)),
                ('dedicated_email', models.EmailField(blank=True, help_text='Dedicated career email created for this candidate', max_length=254)),
                ('dedicated_email_password', models.CharField(blank=True, max_length=200)),
                ('applications_sent', models.IntegerField(default=0)),
                ('cold_pitches_sent', models.IntegerField(default=0)),
                ('interviews_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300)),
                ('role_applied', models.CharField(max_length=300)),
                ('application_type', models.CharField(choices=[('normal', 'Normal (ATS/Portal)'), ('cold', 'Cold Pitch (Direct Outreach)')], max_length=10)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview', 'Interview Scheduled 🎉'), ('rejected', 'Rejected'), ('offer', 'Offer Received 🏆')], default='applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
